/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as RetestRouteImport } from './routes/retest'
import { Route as RunRouteImport } from './routes/run'
import { Route as SuiteRouteImport } from './routes/suite'
import { Route as AgentsOverviewRouteImport } from './routes/agents.overview'
import { Route as ReportIndexRouteImport } from './routes/report.index'
import { Route as ReportFailuresFailureIdRouteImport } from './routes/report.failures.$failureId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RetestRoute = RetestRouteImport.update({
  id: '/retest',
  path: '/retest',
  getParentRoute: () => rootRouteImport,
} as any)
const RunRoute = RunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiteRoute = SuiteRouteImport.update({
  id: '/suite',
  path: '/suite',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsOverviewRoute = AgentsOverviewRouteImport.update({
  id: '/agents/overview',
  path: '/agents/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIndexRoute = ReportIndexRouteImport.update({
  id: '/report/',
  path: '/report/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportFailuresFailureIdRoute = ReportFailuresFailureIdRouteImport.update({
  id: '/report/failures/$failureId',
  path: '/report/failures/$failureId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/retest': typeof RetestRoute
  '/run': typeof RunRoute
  '/suite': typeof SuiteRoute
  '/agents/overview': typeof AgentsOverviewRoute
  '/report/': typeof ReportIndexRoute
  '/report/failures/$failureId': typeof ReportFailuresFailureIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/retest': typeof RetestRoute
  '/run': typeof RunRoute
  '/suite': typeof SuiteRoute
  '/agents/overview': typeof AgentsOverviewRoute
  '/report': typeof ReportIndexRoute
  '/report/failures/$failureId': typeof ReportFailuresFailureIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/retest': typeof RetestRoute
  '/run': typeof RunRoute
  '/suite': typeof SuiteRoute
  '/agents/overview': typeof AgentsOverviewRoute
  '/report/': typeof ReportIndexRoute
  '/report/failures/$failureId': typeof ReportFailuresFailureIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/dashboard'
    | '/retest'
    | '/run'
    | '/suite'
    | '/agents/overview'
    | '/report/'
    | '/report/failures/$failureId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/dashboard'
    | '/retest'
    | '/run'
    | '/suite'
    | '/agents/overview'
    | '/report'
    | '/report/failures/$failureId'
  id:
    | '__root__'
    | '/'
    | '/connect'
    | '/dashboard'
    | '/retest'
    | '/run'
    | '/suite'
    | '/agents/overview'
    | '/report/'
    | '/report/failures/$failureId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectRoute: typeof ConnectRoute
  DashboardRoute: typeof DashboardRoute
  RetestRoute: typeof RetestRoute
  RunRoute: typeof RunRoute
  SuiteRoute: typeof SuiteRoute
  AgentsOverviewRoute: typeof AgentsOverviewRoute
  ReportIndexRoute: typeof ReportIndexRoute
  ReportFailuresFailureIdRoute: typeof ReportFailuresFailureIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retest': {
      id: '/retest'
      path: '/retest'
      fullPath: '/retest'
      preLoaderRoute: typeof RetestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run': {
      id: '/run'
      path: '/run'
      fullPath: '/run'
      preLoaderRoute: typeof RunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suite': {
      id: '/suite'
      path: '/suite'
      fullPath: '/suite'
      preLoaderRoute: typeof SuiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/overview': {
      id: '/agents/overview'
      path: '/agents/overview'
      fullPath: '/agents/overview'
      preLoaderRoute: typeof AgentsOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/': {
      id: '/report/'
      path: '/report'
      fullPath: '/report/'
      preLoaderRoute: typeof ReportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/failures/$failureId': {
      id: '/report/failures/$failureId'
      path: '/report/failures/$failureId'
      fullPath: '/report/failures/$failureId'
      preLoaderRoute: typeof ReportFailuresFailureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectRoute: ConnectRoute,
  DashboardRoute: DashboardRoute,
  RetestRoute: RetestRoute,
  RunRoute: RunRoute,
  SuiteRoute: SuiteRoute,
  AgentsOverviewRoute: AgentsOverviewRoute,
  ReportIndexRoute: ReportIndexRoute,
  ReportFailuresFailureIdRoute: ReportFailuresFailureIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
